### ISSUE TITLE
Link a robot to OAK-D (tilted)

### ISSUE THREAD

**Issue by metanav** [luxonis/depthai-ros#201]
I am trying to connect a robot's base_link (fixed) to the OAK-D's `oak-d_frame`. I can calculate the base_link distance from the camera in the 3D manually. Which is the reference frame, `oak-d_frame` or `oak_rgb_camera_optical_frame`? 

Also, what is the following configuration for? Is it relative to the base_link or I can use the orientation from the IMU (after converting quaternion to Euler)?

depthai_examples/launch/yolov4_publisher.launch.py:

```
    cam_roll  = LaunchConfiguration('cam_roll',      default = '0.0')
    cam_pitch = LaunchConfiguration('cam_pitch',     default = '0.0')
    cam_yaw   = LaunchConfiguration('cam_yaw',       default = '0.0')
```

**Comment by Serafadam** [comment]
Hi, 
You can check out current URDF representation [here](https://github.com/luxonis/depthai-ros/blob/humble/depthai_bridge/urdf/include/depthai_macro.urdf.xacro)
For connecting cameras to the robot you'll want to use `parent_frame` (which defaults to `oak-d-base-frame`). As for the configuration, currently these represent RPY orientation of `base frame`  to the `parent frame`. See how [multicam](https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/launch/example_multicam.launch.py)`example for `depthai_ros_driver` uses those parameters.
Also, are you using mobile robot or manipulator? In case of manipulator you might also want to check out [hand-eye calibration](https://ros-planning.github.io/moveit_tutorials/doc/hand_eye_calibration/hand_eye_calibration_tutorial.html)

**Comment by metanav** [comment]
Thanks, @Serafadam. I think I'm using the same URDF. By the way, I am using a manipulator with the camera mounted overhead  facing to each other at roll = 0,  pitch = 35 degree, yaw = 180 degree. 

<img width="847" alt="Screenshot 2023-01-17 at 22 05 31" src="https://user-images.githubusercontent.com/7456984/212906521-9aa60bc4-0128-4e64-9af2-421af1b32ed0.png">

**Comment by metanav** [comment]
I was able to connect the manipulator's`base_link` to the OAK-D using the following command line.

```
$ ros2 launch depthai_examples  yolov4_publisher.launch.py cam_pos_x:=0.90 cam_pos_y:=0 cam_pos_z:=0.70  \
cam_roll:=0.0 cam_pitch:=0.610865  cam_yaw:=3.14159 parent_frame:=base_link
```

Now the problem is the transform seems not working from the `oak_rgb_camera_optical_frame` to `base_link`. The values are not correct.  Also, I noticed in the output of the `/color/yolov4_Spatial_detections` topic, the `position.y` value is negative but the `oak_rgb_camera_optical_frame` Y-axis is downward so it should be positive if the detected object lies within the positive Y -axis which is the case for the output below.

<img width="726" alt="Screenshot 2023-01-17 at 22 21 25" src="https://user-images.githubusercontent.com/7456984/212909697-5b0df4cf-953e-4dcc-aaee-ea4145d6cdc5.png">


```
---
header:
  stamp:
    sec: 812
    nanosec: 529694938
  frame_id: oak_rgb_camera_optical_frame
detections:
- results:
  - class_id: '41'
    score: 0.0
  bbox:
    center:
      position:
        x: 276.0
        y: 227.0
      theta: 0.0
    size_x: 42.0
    size_y: 0.0
  position:
    x: 0.1272372156381607
    y: -0.035740792751312256
    z: 1.0023199319839478
  is_tracking: false
  tracking_id: ''
---
```
