### ISSUE TITLE
[BUG] {RGBD/Depth pipeline not working with 400P mono resolution}

### ISSUE THREAD

**Issue by borongyuan** [luxonis/depthai-ros#270]
**Describe the bug**
There’s no message on mono image topics and stereo image topic with 400P mono resolution using RGBD or Depth pipeline. 720P mono resolution and 800P mono resolution works well. Only 400P mono resolution have this issue. Only related to Depth pipeline. I can receive mono images with 400P resolution using Stereo or RGBStereo pipeline. It's quite strange and have not found the reason. But it seems to be introduced by (#261).

**Minimal Reproducible Example**
Run depthai_ros_driver with following params.
```
/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_ip: ''
      i_laser_dot_brightness: 800
      i_mx_id: ''
      i_nn_type: none
      i_pipeline_type: RGBD
      i_usb_port_id: ''
      i_usb_speed: SUPER_PLUS
      i_pipeline_dump: false
      i_calibration_dump: false
      i_external_calibration_path: ''
    left:
      i_board_socket_id: 1
      i_calibration_file: ''
      i_get_base_device_timestamp: true
      i_fps: 30.0
      i_height: 400
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: true
      i_simulate_from_topic: false
      i_disable_node: false
      i_resolution: '400'
      i_width: 640
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    rgb:
      i_board_socket_id: 0
      i_simulate_from_topic: false
      i_get_base_device_timestamp: true
      i_disable_node: false
      i_calibration_file: ''
      i_enable_preview: false
      i_fps: 30.0
      i_height: 720
      i_interleaved: false
      i_keep_preview_aspect_ratio: true
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_preview_size: 300
      i_publish_topic: true
      i_resolution: '1080'
      i_set_isp_scale: true
      i_width: 1280
      r_exposure: 20000
      r_focus: 1
      r_iso: 800
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_whitebalance: 3300
    right:
      i_board_socket_id: 2
      i_calibration_file: ''
      i_get_base_device_timestamp: true
      i_fps: 30.0
      i_height: 400
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: true
      i_simulate_from_topic: false
      i_disable_node: false
      i_resolution: '400'
      i_width: 640
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    stereo:
      i_align_depth: true
      i_get_base_device_timestamp: true
      i_output_disparity: false
      i_bilateral_sigma: 0
      i_board_socket_id: 0
      i_depth_filter_size: 5
      i_depth_preset: HIGH_ACCURACY
      i_enable_decimation_filter: false
      i_enable_distortion_correction: false
      i_enable_spatial_filter: false
      i_enable_speckle_filter: false
      i_enable_temporal_filter: false
      i_enable_threshold_filter: false
      i_extended_disp: false
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_lr_check: true
      i_lrc_threshold: 10
      i_max_q_size: 30
      i_rectify_edge_fill_color: 0
      i_stereo_conf_threshold: 255
      i_width: 1280
    use_sim_time: false
```

**Attach system log**
Build v2.7.0-humble on Ubuntu 22.04
Using OAK-D Pro W
