### ISSUE TITLE
[BUG] Camera frequency not respected since 2.8.1

### ISSUE THREAD

**Issue by BriceRenaudeau** [luxonis/depthai-ros#429]
Branch: ROS Iron
Camera: OAK-D-Pro W

**Describe the bug**
Since release 2.8.1 the camera topic frequency has been wrong and unstable (should be 15Hz):
![camera_info_wrong_frequency](https://github.com/luxonis/depthai-ros/assets/48433002/eb37038e-1b0f-481d-9ed9-e3816fb96a07)

**Expected behavior**
It was working great on 2.8.0:
![camera_info_right_frequency](https://github.com/luxonis/depthai-ros/assets/48433002/cdba76ee-6efc-4447-b7f5-de1032f1d238)

**Comment by BriceRenaudeau** [comment]
```yaml
/**:
  ros__parameters:
    rgb:
      i_disable_node: true # no rgb
    camera:
      i_enable_imu: false
      i_enable_ir: true
      i_floodlight_brightness: 0
      i_ip: ''
      i_laser_dot_brightness: 1100 #1100
      i_mx_id: ''
      i_nn_type: none
      i_pipeline_type: depth
      i_usb_port_id: ''
      i_usb_speed: HIGH
      i_pipeline_dump: true
      i_calibration_dump: false
      i_external_calibration_path: ''
    left:
      i_board_socket_id: 1
      i_calibration_file: ''
      i_get_base_device_timestamp: false
      i_fps: 15.0
      i_height: 720
      i_low_bandwidth: false # To reduce bandwith for POE cam
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: true
      i_simulate_from_topic: false
      i_disable_node: false
      i_resolution: '400'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    right:
      i_board_socket_id: 2
      i_calibration_file: ''
      i_get_base_device_timestamp: false
      i_fps: 15.0
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_topic: false
      i_simulate_from_topic: false
      i_disable_node: false
      i_resolution: '400'
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    stereo:
      i_align_depth: false                      # Align with color, not needeed
      i_subpixel: true                          # Allowing further maximum distance, and better accuracy w/in given range. https://docs.luxonis.com/projects/api/en/latest/tutorials/configuring-stereo-depth/#stereo-subpixel-mode
      i_get_base_device_timestamp: false
      i_output_disparity: false                 # For WSL filter
      i_bilateral_sigma: 0                      # For Bilateral Sigma filter
      i_board_socket_id: 2
      i_depth_filter_size: 0                    # For median filter. Disabled as no compatible with extended disparity
      i_disparity_width: DISPARITY_96           # Disparity search range: 64 or 96 pixels are supported by the HW.
      i_set_disparity_to_depth_use_spec_translation: false # To use calibration setero entrax
      i_enable_companding: true                # Disparity companding using sparse matching. Matching pixel by pixel for N disparities. Matching every 2nd pixel for M disparitites. Matching every 4th pixel for T disparities. In case of 96 disparities: N=48, M=32, T=16. This way the search range is extended to 176 disparities, by sparse matching. Note: when enabling this flag only depth map will be affected, disparity map is not
      i_extended_disp: true                     # Supporting closer-in minimum depth (by a factor of 2): Extended disparity
      i_subpixel_fractional_bits: 5              # Increase to 5 to reduce layering effect
      # i_depth_preset: HIGH_ACCURACY           # Conflicts with some other params when manually set. HIGH_ACCURACY: prefers accuracy over density. More invalid depth values, but less outliers.
      i_enable_decimation_filter: false         # For decimation filter
      i_decimation_filter_decimation_factor: 2  # For decimation filter. Not used
      i_enable_distortion_correction: true      # For correcting lense distorsion, should be left to true
      i_enable_spatial_filter: false            # For Spation filter. Not used
      i_spatial_filter_hole_filling_radius: 2   #
      i_spatial_filter_alpha: 0.5               #
      i_spatial_filter_delta: 20                #
      i_spatial_filter_iterations: 1            #
      i_enable_speckle_filter: false            # For speckle filter. To check
      i_speckle_filter_speckle_range: 200
      i_enable_temporal_filter: false           # For temporal filter, not used (no sense on a moving robot)
      i_enable_threshold_filter: true          # For range filtering. To check
      i_threshold_filter_min_range: 0
      i_threshold_filter_max_range: 5000
      i_height: 720
      i_low_bandwidth: false
      i_low_bandwidth_quality: 50
      i_lr_check: true                        # Eliminating shadowing from running disparity in only one direction: left/right check (runs disparity in both directions)
      i_lrc_threshold: 10
      i_max_q_size: 30
      i_rectify_edge_fill_color: 0
      i_stereo_conf_threshold: 150
      i_width: 1280
      i_enable_brightness_filter: true
      i_brightness_filter_min_brightness: 10
      i_brightness_filter_max_brightness: 254
```
