### ISSUE TITLE
[BUG] {Node crash after specification of IP or mxid}

### ISSUE THREAD

**Issue by spajder16** [luxonis/depthai-ros#458]
Hi, I'm trying to run multiple cameras at once with Ros driver. To do that I want to specify the IP address or mxid of the cameras, but when I'm doing that the launch crashes.
Here is my launch file:
```
<?xml version="1.0"?>
<launch>
    <rosparam file="$(find luxonis_cameras)/config/multicam.yaml" />
    <include file="$(find depthai_ros_driver)/launch/camera.launch">
        <arg name="name" value="oak_d_w"/>
    </include>
</launch>
```

And my multicam.yaml config file:
```
/oak_d_w:
  camera_i_ip: 192.168.1.149
  camera_i_pipeline_type: RGB
  camera_i_nn_type: none
  rgb_i_low_bandwidth: true
  rgb_i_low_bandwidth_quality: 50

```
When I run it I get:
![Zrzut ekranu 2023-11-16 121745](https://github.com/luxonis/depthai-ros/assets/9286759/07fdac92-299d-4ab4-a001-a4c9ba8fdbfe)

but when I delete the camera_i_ip
so the config file looks like this:
```
/oak_d_w:
  camera_i_pipeline_type: RGB
  camera_i_nn_type: none
  rgb_i_low_bandwidth: true
  rgb_i_low_bandwidth_quality: 50

```
the node works
![Zrzut ekranu 2023-11-16 141650](https://github.com/luxonis/depthai-ros/assets/9286759/c96951a4-1922-40c1-a600-93c96cd76ae2)
