### ISSUE TITLE
[BUG] CameraInfo not "reasonable"

### ISSUE THREAD

**Issue by fwarmuth** [luxonis/depthai-ros#467]
Hey,
my overall goal is to do an **extrinsic calibration using the MoveIT camera calibration.**
### Situation:
System: **ros1 noetic docker container**
I run the `rgb_pcl.launch` with a custom param_file:
```
/oak:
    camera_i_ip: 192.168.4.169
    camera_i_floodlight_brightness: 800
    camera_i_laser_dot_brightness: 1000
    camera_i_pipeline_type: RGBD
    camera_i_nn_type: none
    rgb_i_resolution: '1080P'
    rgb_r_focus: 125
    rgb_r_set_man_focus: true
    left_i_resolution: '720P'
    right_i_resolution: '720P'
    stereo_i_resolution: '720P'
    stereo_i_stereo_conf_threshold: 255
    stereo_i_subpixel: true
    stereo_i_extended_disp: true
    stereo_i_depth_filter_size: 5
```
It publishes everything, except `/oak/points` don't know why, but problem for a different day. (Maybe some one has a hint)
I receive a CameraInfoMsg similar to:
```
header: 
  seq: 30204
  stamp: 
    secs: 1701155449
    nsecs: 762082437
  frame_id: "oak_rgb_camera_optical_frame"
height: 720
width: 1280
distortion_model: "rational_polynomial"
D: [-0.9029932618141174, -54.66876220703125, 0.00040832499507814646, 0.00043196146725676954, 411.0915832519531, -1.0839022397994995, -52.5931510925293, 401.5426940917969]
K: [1039.033447265625, 0.0, 628.4920654296875, 0.0, 1039.033447265625, 374.26031494140625, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [1039.033447265625, 0.0, 628.4920654296875, 0.0, 0.0, 1039.033447265625, 374.26031494140625, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
All good right?
### Problem:
The MoveIT Camera Calibration Target module, shouts:
**Target detector has not received reasonable intrinsics. Attempted detection anyway.**
If one looks in the source code, it does call `areIntrinsicsReasonable()` -> Definition at line [292](https://docs.ros.org/en/api/moveit_calibration_plugins/html/handeye__target__base_8h_source.html#l00292) of file [handeye_target_base.h](https://docs.ros.org/en/api/moveit_calibration_plugins/html/handeye__target__base_8h_source.html).

Therefore it seems that the published (`/oak/rgb/camera_info`) camera info data is not correct. What can i do about it, i dont want to calibrate the camera by hand - as it provides factory calibration values. 

Any hints or pushes in the right direction would be highly appreciated!
Cheers
