### ISSUE TITLE
[BUG] rgbd_pcl inconsistent Resolution configuration

### ISSUE THREAD

**Issue by TheMarksniper** [luxonis/depthai-ros#515]
[log_system_information.json](https://github.com/luxonis/depthai-ros/files/14724547/log_system_information.json)
Description:
Running the `rgbd_pcl.launch.py` launcher file from `depthai_ros_driver` package with custom `params_file` is yielding an inconsistent resolution.
Specified resolution (1920x1080, 1080P) set and checked against parameters `ros2 param dump /oak` and camera info `ros2 topic echo /oak/rgb/camera_info` give the right resolution. Inconsistency comes with the `oak/rgb/image_raw` topic as the output gives resolution of 1280x720. This problem is not present for the stereo topic as it changes properly according to the parameters.

used parameter file:
```

/oak:

  ros__parameters:

    camera:
      i_nn_type: none
      i_enable_ir: true
      i_laser_dot_brightness: 1200
      i_floodlight_brightness: 1500
      i_ip: 192.168.8.23

    rgb:
      i_resolution: 1080P
      i_width: 1920
      i_height: 1080
      rgb_i_set_isp_scale: true
      i_max_q_size: 1
      i_fps: 10.0

    stereo:
      i_subpixel: false
      i_enable_disparity_shift: true
      i_disparity_shift: 50
      i_max_q_size: 1
      i_align_depth: true

    right:
      i_resolution: 400P
      i_max_q_size: 1
      i_fps: 10.0

    left:
      i_resolution: 400P
      i_max_q_size: 1
      i_fps: 10.0

```
Error also exists while running  - `camera` in `depthai_ros_driver` with same resolution parameters

Expected behavior:
Image height and width being the same in the params ,camera_info and image_raw topics

Attached log:
OS: Ubuntu 22.04.4 LTS
ROS: ROS2 Humble
Depthai installation: apt install

![image](https://github.com/luxonis/depthai-ros/assets/91737012/b9fa1e4b-6895-42c8-b105-a2fe9b71a592)
![image](https://github.com/luxonis/depthai-ros/assets/91737012/a9d44f78-362a-468f-aee5-1905ad0916cf)
![image](https://github.com/luxonis/depthai-ros/assets/91737012/b1e432b6-3254-4ba5-b63f-164524ddbca4)
[log_system_information.json](https://github.com/luxonis/depthai-ros/files/14724551/log_system_information.json)
