### ISSUE TITLE
[BUG] {not able to set rgb resolution with ros2 driver}

### ISSUE THREAD

**Issue by lukas-czy** [luxonis/depthai-ros#565]
# the bug
When starting the [ros2 driver](https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/launch/camera.launch.py) and altering the param file, I am not able to set the resolution. As soon as I change to a valid configuration except the default one, I receive this:
```
[component_container-1] [INFO] [1721766981.178370161] [oak]: Device type: OAK-1
[component_container-1] [INFO] [1721766981.180253902] [oak]: Pipeline type: RGB
[component_container-1] [WARN] [1721766981.213315796] [oak]: Spatial NN selected, but configuration is RGB. Please change camera.i_nn_type parameter to RGB.
[component_container-1] [INFO] [1721766981.213438722] [oak]: Finished setting up pipeline.
[component_container-1] [INFO] [1721766981.391528344] [oak]: Camera ready!
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/oak' in container '/oak_container'
[component_container-1] [ERROR] [1721766982.327924649] [oak]: No data on logger queue!
[component_container-1] [ERROR] [1721766982.328234797] [oak]: Camera diagnostics error: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'sys_logger_queue' (X_LINK_ERROR)'
```
The launch file was configured to use my own configuration.yaml. It was altered in line 131 in this way:
```
DeclareLaunchArgument("params_file", default_value=os.path.join(depthai_prefix, 'config', 'camera.yaml')),
```
to
```
DeclareLaunchArgument("params_file", default_value="/ros2_ws/src/camera_utils/launch/camera.yaml"),
```
the camera.yaml looks like this:
```
/oak:
  ros__parameters:
    camera:
      i_enable_imu: false
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGB
    rgb:
      i_resolution: 4K
      i_height: 2160
      i_width: 3840
      i_set_isp_scale: false
```
as I said, when running the same setup with ```i_resolution: 1080P``` it works. It also works when using a random value like  ```i_resolution: abc``` as it uses the default config instead. Therefore 4K looks like a valid but not working option.
**Minimal Reproducible Example**
# the setup
A OAK-1 is connected to a raspberry Pi 5 running Ubuntu24.04. The ros environment is containerized based on this dockerfile:
```
FROM microros/micro-ros-agent:humble AS base

# Base Dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-rosdep \
    python3-colcon-common-extensions \
    build-essential

# ROS2 specific Dependencies
WORKDIR /ros2_ws
RUN rosdep init && rosdep update

FROM base AS depthai

RUN apt-get update && apt-get install -y ros-humble-depthai-ros

FROM depthai AS utils
RUN apt-get update && apt-get install -y --no-install-recommends \
    '~nros-humble-rqt*' \
    nano \
    iputils-ping

FROM utils AS app

# Run the container forever
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
```
the container is started with this docker compose:
```
version: '3.8'

services:
  ros2_environment:
    image: ros2_environment:dev
    container_name: ros2_env
    command: tail -f /dev/null
    privileged: true
    device_cgroup_rules:
      - 'c 189:* rmw'
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/ros2_ws
```
This should be enough to reconstruct the error

# Expected Behavior
The 4K Resolution (or any other except the default) is used by the 
**Screenshots**
