### ISSUE TITLE
camera_info P matrices are zero

### ISSUE THREAD

**Issue by peci1** [luxonis/depthai-ros#58]
I launched depthai_examples rgb_stereo_node.launch and I noticed the camera_info of both the RGB and stereo cameras have all zeros in the P component. This practically makes depth_image_proc unusable with the images.

**Comment by peci1** [comment]
Example:

```
header: 
  seq: 6333
  stamp: 
    secs: 1642079111
    nsecs: 580556369
  frame_id: "oak_rgb_camera_optical_frame"
height: 720
width: 1280
distortion_model: "rational_polynomial"
D: [1.2615910768508911, -57.75300216674805, 0.0008713369606994092, 0.0013280882267281413, 282.6454772949219, 1.1072325706481934, -56.35382843017578, 277.4756164550781]
K: [1033.0888671875, 0.0, 646.242919921875, 0.0, 1031.7818603515625, 369.31561279296875, 0.0, 0.0, 1.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

```
