### ISSUE TITLE
IMU data streams are not in the real time (delayed)

### ISSUE THREAD

**Issue by Jenanaputra** [luxonis/depthai-ros#605]
Hey. ......

I am using ROS2 Humble in Ubuntu 22.04. I installed the driver from ros binaries.

I tried to launch the camera.launch.py by setting it with this configurations :

```
/oak:
  ros__parameters:
    rgb:
    # # ISP scaling  #
    #   i_isp_den: 5
    #   i_isp_num: 3
    # low bandwidth  #     
      i_low_bandwidth: true
    left:
      i_low_bandwidth: true
    right:
      i_low_bandwidth: true
    stereo:
      # i_low_bandwidth: true
      i_subpixel: true
    imu:
      i_enable_rotation: true
      # i_sync_method: COPY
```

I am using OAK-D POE. Do you guys know how to improve the update rate of IMU ?  Cause I have the delayed data
