### ISSUE TITLE
[BUG] camera gets stuck with ros

### ISSUE THREAD

**Issue by DanielCyberbee** [luxonis/depthai-ros#608]
**Check if issue already exists**

- Google it (e.g. *error xy* github luxonis depthai)
- Check [troubleshooting](https://docs.luxonis.com/en/latest/pages/troubleshooting/) in documentation.

**Describe the bug**

**Minimal Reproducible Example**
Append the MRE to the bug report, [instructions here](https://docs.luxonis.com/en/latest/pages/support/#creating-minimal-reproducible-example)

If available launch files don't work in your case, please check if you also get errors while running:
- `stereo_inertial_node` in `depthai_examples`
- `camera` in `depthai_ros_driver`
- In case both fail to run, please check if you can run [the default python demo app](https://docs.luxonis.com/en/latest/#demo-script)

**Expected behavior**

**Screenshots**

**Pipeline Graph**

Please also provide a screenshot of your pipeline using the [DepthAI Pipeline Graph](https://github.com/geaxgx/depthai_pipeline_graph).

You can save it in `depthai_ros_driver`, either by calling `/save_pipeline` ROS service, or by setting parameter `camera.i_pipeline_dump` in ROS 2 or `camera_i_pipeline_dump` in ROS. Pipeline dump is saved to `/tmp/pipeline.json`.

**Attach system log**
 - Provide output of [log_system_information.py](https://github.com/luxonis/depthai/blob/main/log_system_information.py)
 - Which OS/OS version are you using?
 - Which ROS version are you using?
 - Which ROS distribution are you using ?
 - Is `depthai-ros` built from source or installed from apt?
 - Is `depthai/depthai-core` library installed from rosdep or manually? For rosdep install, check if `ros-<rosdistro>-depthai` package is installed, manual install can be checked with `ldconfig -p | grep depthai`
 - Please include versions of following packages - `apt show ros-$ROS_DISTRO-depthai ros-$ROS_DISTRO-depthai-ros ros-$ROS_DISTRO-depthai-bridge ros-$ROS_DISTRO-depthai-ros-msgs ros-$ROS_DISTRO-depthai-ros-driver`
 - To get additional logs, set `DEPTHAI_DEBUG=1` and paste the logs, either from command line or from latest log in `~/.ros/log`

**Additional context**

**Comment by Serafadam** [comment]
Hi, could you fill out the debug information?

**Comment by DanielCyberbee** [comment]
When I'm trying to run a ROS program with the camera (OAK-D pro), the video from the relevant topics appears stuck. Meaning it captures frames much slower compared to any other camera. Any ideas on how to solve it?

**Comment by Serafadam** [comment]
On what distribution does this happen? 
What is you PC configuration and network setup? 
If using DDS, which one?
Does this happen when running depthai_ros_drivers' executable, or stereo_inertial_node?
Is the repository built from source or downloaded from APT?

**Comment by BryanBetancur** [comment]
Hello, I'm having a similar problem, when I use `python3 -m depthai_viewer` the rgb, depth and pointcloud seems pretty stable and fast, but when I use `ros2 launch depthai_ros_driver camera.launch.py` the rgb, depth and pointcloud start to get a lot of lag.

- RMW_IMPLEMENTATION: `rmw_cyclonedds_cpp`
- depthai-core compiled mannually on `main` branch
- depthai-ros commit: `0022aa3c70084054cbe2b9d36c8ec28ca9f5b4c0`
- Jetson Orin AGX 64gb
- OAK-D-PRO-W-POE

Using the following parameters:
```
/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_dump: false
    rgb:
      i_low_bandwidth: true
      i_resolution: 720P
    left:
      i_low_bandwidth: true
    right:
      i_low_bandwidth: true
    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_right_rect_publish_topic: true
      i_right_rect_synced: false
      i_low_bandwidth: true
      i_decimation_filter_decimation_factor: 8
```

Pipeline:

[14442C103110F4D600_pipeline.json](https://github.com/user-attachments/files/19216421/14442C103110F4D600_pipeline.json)
