### ISSUE TITLE
[BUG] {Compressed Images being published while parameter is set to false}

### ISSUE THREAD

**Issue by dwffls** [luxonis/depthai-ros#637]
**Describe the bug**
Even though i_publish_compressed is set to false, publishers are still being created and published on.

**Minimal Reproducible Example**
```yaml
camera:
  i_nn_type: none
  i_pipeline_type: Depth
stereo:
    i_extended_disp: true
    i_publish_compressed: False
right:
  i_publish_topic: true
  i_publish_compressed: False
```
Above settings are used on an OAK-D-SR camera, running iron build of depthai-ros

**Expected behavior**
When publish_compressed set to false it should not published
