### ISSUE TITLE
"StereoDepth(7) - No output of StereoDepth is connected/used!" when launching v2.10.5-humble

### ISSUE THREAD

**Issue by grusel-opi** [luxonis/depthai-ros#655]
Hello,
I am using oakd pro on a raspberry pi 4b running Ubuntu 22.04 (on turtlebot4) with ros2 humble. Since i want to use the newer features of the driver i build v2.10.5-humble from source.

When launching the driver the following output occurs:
```

[component_container-6] [INFO] [1736869993.432551551] [oakd]: Starting camera.
[component_container-6] [INFO] [1736869993.450956308] [oakd]: No ip/mxid specified, connecting to the next available device.
[component_container-6] [INFO] [1736869996.702183838] [oakd]: Camera with MXID: 1844301031F9AC0F00 and Name: 1.1.2 connected!
[component_container-6] [INFO] [1736869996.704014151] [oakd]: USB SPEED: HIGH
[component_container-6] [INFO] [1736869996.753688020] [oakd]: Device type: OAK-D-PRO
[component_container-6] [INFO] [1736869996.764343364] [oakd]: Pipeline type: RGBD
[component_container-6] [INFO] [1736869997.386184310] [oakd]: Decimation filter enabled with decimation factor 2. Previous width and height: 1280 x 720, after decimation: 640 x 360
[component_container-6] [INFO] [1736869997.631370103] [oakd]: Finished setting up pipeline.
[component_container-6] terminate called after throwing an instance of 'std::runtime_error'
[component_container-6]   what():  StereoDepth(7) - No output of StereoDepth is connected/used!

```
The parameter list used is the following:

```
/oakd:
  ros__parameters:
    camera:
      i_calibration_dump: false
      i_enable_diagnostics: true
      i_enable_ir: true
      i_enable_sync: true
      i_external_calibration_path: ""
      i_floodlight_brightness: 0
      i_ip: ""
      i_laser_dot_brightness: 800
      i_mx_id: ""
      i_nn_type: none
      i_pipeline_dump: false
      i_pipeline_type: RGBD
      i_publish_tf_from_calibration: false
      i_restart_on_diagnostics_error: false
      i_rs_compat: false
      i_tf_base_frame: oak
      i_tf_cam_pitch: "0.0"
      i_tf_cam_pos_x: "0.0"
      i_tf_cam_pos_y: "0.0"
      i_tf_cam_pos_z: "0.0"
      i_tf_cam_roll: "0.0"
      i_tf_cam_yaw: "0.0"
      i_tf_camera_model: ""
      i_tf_camera_name: oak
      i_tf_custom_urdf_location: ""
      i_tf_custom_xacro_args: ""
      i_tf_imu_from_descr: "false"
      i_tf_parent_frame: oak-d-base-frame
      i_usb_port_id: ""
      i_usb_speed: SUPER_PLUS
      i_enable_diagnostics: true
      i_enable_imu: false
    diagnostic_updater:
        period: 1.0
    imu:
      i_acc_cov: 0.0
      i_acc_freq: 400
      i_batch_report_threshold: 5
      i_enable_rotation: false
      i_get_base_device_timestamp: false
      i_gyro_cov: 0.0
      i_gyro_freq: 400
      i_mag_cov: 0.0
      i_max_batch_reports: 10
      i_message_type: IMU
      i_rot_cov: -1.0
      i_sync_method: LINEAR_INTERPOLATE_ACCEL
      i_update_ros_base_time_on_ros_msg: false
    left:
      i_add_exposure_offset: false
      i_board_socket_id: 1
      i_calibration_file: ""
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_exposure_offset: 0
      i_fps: 5.0
      # i_fsync_continuous: false
      # i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 720
      i_low_bandiwdth_frame_freq: 30
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 720P
      i_reverse_stereo_socket_order: false
      i_sensor_img_orientation: AUTO
      i_set_isp3a_fps: false
      i_simulate_from_topic: false
      i_simulated_topic_name: ""
      i_synced: true
      i_update_ros_base_time_on_ros_msg: false
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    rgb:
      i_add_exposure_offset: false
      i_board_socket_id: 0
      i_calibration_file: ""
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_enable_preview: false
      i_exposure_offset: 0
      i_fps: 5.0
      # i_fsync_continuous: false
      # i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 720
      i_interleaved: false
      i_isp_den: 3
      i_isp_num: 2
      i_keep_preview_aspect_ratio: true
      i_low_bandiwdth_frame_freq: 30
      i_low_bandwidth: true
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_output_isp: true
      i_preview_height: 300
      i_preview_size: 300
      i_preview_width: 300
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 1080P
      i_reverse_stereo_socket_order: false
      i_sensor_img_orientation: AUTO
      i_set_isp3a_fps: false
      i_set_isp_scale: true
      i_simulate_from_topic: false
      i_simulated_topic_name: ""
      i_synced: true
      i_update_ros_base_time_on_ros_msg: false
      i_width: 1280
      r_exposure: 20000
      r_focus: 1
      r_iso: 800
      r_set_man_exposure: false
      r_set_man_focus: false
      r_set_man_whitebalance: false
      r_whitebalance: 3300
    right:
      i_add_exposure_offset: false
      i_board_socket_id: 2
      i_calibration_file: ""
      i_disable_node: false
      i_enable_feature_tracker: false
      i_enable_lazy_publisher: true
      i_enable_nn: false
      i_exposure_offset: 0
      i_fps: 5.0
      # i_fsync_continuous: false
      # i_fsync_trigger: false
      i_get_base_device_timestamp: false
      i_height: 720
      i_low_bandiwdth_frame_freq: 30
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_max_q_size: 30
      i_publish_compressed: false
      i_publish_topic: true
      i_resolution: 720P
      i_reverse_stereo_socket_order: false
      i_sensor_img_orientation: AUTO
      i_set_isp3a_fps: false
      i_simulate_from_topic: false
      i_simulated_topic_name: ""
      i_synced: true
      i_update_ros_base_time_on_ros_msg: false
      i_width: 1280
      r_exposure: 1000
      r_iso: 800
      r_set_man_exposure: false
    stereo:
      i_add_exposure_offset: false
      i_align_depth: true
      i_bilateral_sigma: 0
      i_board_socket_id: 0
      i_depth_filter_size: 5
      #i_depth_preset: HIGH_ACCURACY
      #i_disparity_width: DISPARITY_96
      i_enable_alpha_scaling: false
      i_alpha_scaling: 0.0
      i_enable_brightness_filter: false
      i_brightness_filter_min_brightness: 0
      i_brightness_filter_max_brightness: 256
      i_enable_companding: false
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_mode: NON_ZERO_MEDIAN
      i_decimation_filter_decimation_factor: 2
      i_enable_disparity_shift: false
      i_disparity_shift: 0
      i_enable_distortion_correction: false
      i_enable_lazy_publisher: true
      i_enable_spatial_filter: false
      i_spatial_filter_hole_filling_radius: 2
      i_spatial_filter_alpha: 0.5
      i_spatial_filter_delta: 20
      i_spatial_filter_iterations: 1
      i_enable_spatial_nn: false
      i_enable_speckle_filter: false
      i_speckle_filter_speckle_range: 50
      i_enable_temporal_filter: false
      i_temporal_filter_alpha: 0.4
      i_temporal_filter_delta: 20
      i_temporal_filter_persistency: PERSISTENCY_OFF # VALID_2_IN_LAST_3, VALID_8_OUT_OF_8, PERSISTENCY_OFF, PERSISTENCY_INDEFINITELY
      i_enable_threshold_filter: false
      i_threshold_filter_min_range: 400 # what are these values?
      i_threshold_filter_max_range: 15000
      i_exposure_offset: 0
      i_extended_disp: false
      i_get_base_device_timestamp: false
      i_height: 720
      i_left_rect_add_exposure_offset: false
      i_left_rect_enable_feature_tracker: false
      i_left_rect_exposure_offset: 0
      i_left_rect_low_bandwidth: false
      i_left_rect_low_bandwidth_bitrate: 0
      i_left_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_left_rect_low_bandwidth_frame_freq: 30
      i_left_rect_low_bandwidth_profile: 4
      i_left_rect_low_bandwidth_quality: 50
      i_left_rect_publish_compressed: false
      # i_left_rect_synced: true
      i_left_socket_id: 1
      i_low_bandwidth: false
      i_low_bandwidth_bitrate: 0
      i_low_bandwidth_ffmpeg_encoder: libx264
      i_low_bandwidth_profile: 4
      i_low_bandwidth_quality: 50
      i_lr_check: true
      i_lrc_threshold: 10
      i_max_q_size: 30
      i_output_disparity: false
      i_publish_left_rect: false
      i_publish_right_rect: false
      # i_publish_synced_rect_pair: false
      i_publish_topic: true
      i_rectify_edge_fill_color: 0
      i_reverse_stereo_socket_order: false
      i_right_rect_add_exposure_offset: false
      i_right_rect_enable_feature_tracker: false
      i_right_rect_exposure_offset: 0
      i_right_rect_low_bandwidth: false
      i_right_rect_low_bandwidth_bitrate: 0
      i_right_rect_low_bandwidth_ffmpeg_encoder: libx264
      i_right_rect_low_bandwidth_frame_freq: 30
      i_right_rect_low_bandwidth_profile: 4
      i_right_rect_low_bandwidth_quality: 50
      i_right_rect_publish_compressed: false
      # i_right_rect_synced: true
      i_right_socket_id: 2
      i_set_disparity_to_depth_use_spec_translation: false
      i_set_input_size: false
      i_socket_name: rgb
      i_spatial_nn_source: right
      i_stereo_conf_threshold: 100
      i_subpixel: true
      i_subpixel_fractional_bits: 3
      i_synced: true
      i_update_ros_base_time_on_ros_msg: false
      i_width: 1280
    use_sim_time: false
```

```
ldconfig -p | grep depthai:
        libdepthai-opencv.so (libc6,AArch64) => /usr/local/lib/libdepthai-opencv.so
        libdepthai-core.so (libc6,AArch64) => /usr/local/lib/libdepthai-core.so

```
Is there a misconfiguration of parameters for this version of the driver?
