### ISSUE TITLE
Cannot display with rviz2 point cloud when launching camera.launch.py

### ISSUE THREAD

**Issue by DanieleMarchisotti** [luxonis/depthai-ros#659]
**Describe the bug**
I cannot display point cloud with rviz2 when launching camera.launch.py.
```
ros2 launch depthai_ros_driver camera.launch.py
```
I get the following error:
```
[point_cloud_xyzrgb_node]: New subscription discovered on topic '/oak/points', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
```
then if I change HistoryPolicy and ReliabilityPolicy to "System Default" and "Best Effort" respectively on rviz2, I get the following:
```
Message Filter dropping message: frame 'oak_rgb_camera_optical_frame' at time 1738687835.953 for reason 'discarding message because the queue is full'
```

This is my `camera.yaml` file:

```
/**:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: true
      i_nn_type: spatial
      i_pipeline_type: RGBD
      i_enable_sync: true
    right:
      i_publish_topic: true
    left:
      i_publish_topic: true
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
    pipeline_gen:
      i_enable_sync: true
    imu:
      i_enable_rotation: true
      i_get_base_device_timestamp: true
    rgb:
      i_publish_topic: true
    stereo:
      i_publish_topic: true
      i_synced: true
```
However, it seems that with `ros2 topic echo /oak/points` it is possible to see the list of points of the point cloud.
Is it correct? How can I see the point cloud with `camera.launch.py`?
