### ISSUE TITLE
[BUG] distorted decimated pointcloud

### ISSUE THREAD

**Issue by nturro** [luxonis/depthai-ros#675]
hello,

when decimating a pointcloud, the pointcloud is distorted.

The correct pointcloud is displayed here on rviz :

![Image](https://github.com/user-attachments/assets/375c5fd8-8adb-42e3-a3b9-8b112bc3f887)

The distorted (same camera angle view) : 

![Image](https://github.com/user-attachments/assets/6c2e4f03-fb8d-4ee0-bc86-f7e0bda820e8)

It might be related to https://github.com/luxonis/depthai-python/issues/1034

environement : luxonis/depthai-ros:humble-latest container 
 
command (pointcloud.launch.py is the original one):
``` 
ros2 launch depthai_ros_driver pointcloud.launch.py params_file:='/root/luxonis/pcl.yaml
```

tweaked camera config pcl.yaml

```
/oak:
  ros__parameters:
    camera:
      i_nn_type: none
    left:
      i_resolution: '400P'
    right:
      i_resolution: '400P'

    stereo:
      i_align_depth: true
      i_board_socket_id: 2
      i_subpixel: true
      i_right_rect_publish_topic: true
      i_right_rect_synced: false
      i_enable_decimation_filter: true
      i_decimation_filter_decimation_factor: 1
      i_decimation_filter_decimation_mode: PIXEL_SKIPPING
```

Could you help me ?
